// Every value that arrives from a socket is untrusted: it may be the wrong
// type, huge, or crafted to confuse the engine. These guards turn raw event
// payloads into clean values or null, before anything else sees them.
import { type Card, RANKS, type Rank, SUITS, type Suit } from '@twenty-eight/engine';

export function asObject(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

// Room codes are generated by the client from an unambiguous alphabet.
const ROOM_CODE = /^[A-Z0-9]{4,8}$/;
export function parseRoomCode(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const code = value.trim().toUpperCase();
  return ROOM_CODE.test(code) ? code : null;
}

// The per-browser secret that lets a player reclaim their seat. It must be
// long and random enough that nobody can guess another player's.
const PLAYER_ID = /^[A-Za-z0-9_-]{16,64}$/;
export function parsePlayerId(value: unknown): string | null {
  return typeof value === 'string' && PLAYER_ID.test(value) ? value : null;
}

// Display names are shown to every player at the table. Strip control and
// invisible formatting characters (zero-width joiners, bidirectional
// overrides) that could make one name impersonate another, collapse
// whitespace, and cap the length.
export function sanitizeName(value: unknown): string {
  if (typeof value !== 'string') return 'Player';
  const cleaned = value
    .slice(0, 200)
    .normalize('NFC')
    .replace(/[\p{Cc}\p{Cf}\p{Zl}\p{Zp}]/gu, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 20)
    .trim();
  return cleaned || 'Player';
}

export function parseCard(value: unknown): Card | null {
  const o = asObject(value);
  const suit = o.suit;
  const rank = o.rank;
  if (typeof suit !== 'string' || typeof rank !== 'string') return null;
  if (!SUITS.includes(suit as Suit) || !RANKS.includes(rank as Rank)) return null;
  return { suit: suit as Suit, rank: rank as Rank };
}

export function parseBid(value: unknown): 'pass' | number | null {
  if (value === 'pass') return 'pass';
  return typeof value === 'number' && Number.isInteger(value) && value >= 1 && value <= 28 ? value : null;
}

export function parseBaseCards(value: unknown): number {
  return value === 3 || value === 9 ? value : 6;
}
